#!/usr/bin/env python3
"""
Search for ALL possible private keys in wallet.dat
"""

import sqlite3
from binascii import hexlify
import re

# Read wallet.dat
conn = sqlite3.connect('ref_materials/test_wallet.dat')
cursor = conn.cursor()

print("=== Searching wallet.dat for all possible keys ===\n")

# Get all tables
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
tables = cursor.fetchall()
print(f"Tables in database: {[t[0] for t in tables]}\n")

# Search all tables
all_keys = set()

for table in tables:
    table_name = table[0]
    print(f"Searching table: {table_name}")
    
    try:
        cursor.execute(f"PRAGMA table_info({table_name})")
        columns = cursor.fetchall()
        
        # Get all data from table
        cursor.execute(f"SELECT * FROM {table_name}")
        rows = cursor.fetchall()
        
        for row in rows:
            for col_data in row:
                if isinstance(col_data, bytes) and len(col_data) >= 32:
                    # Look for 32-byte sequences that could be private keys
                    for i in range(len(col_data) - 31):
                        key_candidate = col_data[i:i+32]
                        key_hex = hexlify(key_candidate).decode()
                        
                        # Check if it looks like a valid private key
                        if (key_hex != '0' * 64 and 
                            key_hex != 'f' * 64 and
                            len(set(key_hex)) > 4):  # Has some entropy
                            
                            # Check for DER encoding
                            if i >= 2 and col_data[i-2] == 0x04 and col_data[i-1] == 0x20:
                                all_keys.add(('DER-encoded', key_hex))
                            # Check for raw key
                            elif re.match(r'^[0-9a-f]{64}$', key_hex):
                                # Additional entropy check
                                if len(set(key_hex)) > 8:
                                    all_keys.add(('Raw', key_hex))
                elif isinstance(col_data, str) and len(col_data) >= 64:
                    # Check for hex-encoded keys in text
                    hex_pattern = r'[0-9a-fA-F]{64}'
                    matches = re.findall(hex_pattern, col_data)
                    for match in matches:
                        if match.lower() != '0' * 64 and match.lower() != 'f' * 64:
                            all_keys.add(('Hex string', match.lower()))
    except Exception as e:
        print(f"  Error reading table: {e}")

conn.close()

print(f"\n=== Found {len(all_keys)} unique potential private keys ===\n")

for key_type, key_hex in sorted(all_keys):
    print(f"{key_type}: {key_hex}")

print("\n=== Summary ===")
print(f"Total unique keys found: {len(all_keys)}")
print("\nThese are all potential private keys found in wallet.dat.")
print("The expected address alpha1q64c7vmezvqd43l4g0hg8l72uttc0sc5cqrhpqz")
print("might be generated by:")
print("1. One of these keys directly")
print("2. A key derived from one of these")
print("3. A key not present in this wallet.dat file")